import { Link } from "react-router-dom";
import { usePromptStore } from "../stores/PromptStore";
import { useEffect } from "react";

const ResultPrompt = () => {
  const prompt = usePromptStore((state) => state.prompt);
  const processPrompt = usePromptStore((state) => state.processPrompt);
  const result = usePromptStore((state) => state.result);

  if (!prompt.text || prompt.text === "") {
    return (
      <div className="flex flex-col justify-center items-center gap-2 h-screen">
        <h1 className="font-bold">Result Prompt</h1>
        <p>No hay prompt seleccionado</p>
        <Link className="btn btn-accent" to={"/"}>
          Volver al inicio
        </Link>
      </div>
    );
  }

  useEffect(() => {
    async function fetchData() {
      const response = await processPrompt();
      console.log(response);
    }

    fetchData();
  }, []);

  if (!result) {
    return (
      <div className="flex flex-col justify-center items-center gap-2 h-screen">
        <p className="text-xl">Procesando</p>
        <span className="loading loading-dots w-[5rem]"></span>
      </div>
    );
  }

  return (
    <div className="flex flex-col justify-center items-center gap-2 h-screen">
      <h1 className="font-bold">Result Prompt</h1>
      <p>{prompt.text}</p>
      <div className="artboard artboard-horizontal phone-6 bg-slate-500">
        <img src={result.result.data.url} alt="Image generated by IA" />
      </div>
      <Link className="btn btn-accent" to={"/"}>
        Volver al inicio
      </Link>
    </div>
  );
};

export default ResultPrompt;
