import { Link } from "react-router-dom";
import { usePromptStore } from "../stores/PromptStore";
import { useEffect } from "react";
import ConfettiExplosion from "react-confetti-explosion";

const ResultPrompt = () => {
  const prompt = usePromptStore((state) => state.prompt);
  const processPrompt = usePromptStore((state) => state.processPrompt);
  const result = usePromptStore((state) => state.result);

  if (!prompt.text || prompt.text === "") {
    return (
      <div className="flex flex-col justify-center items-center gap-2 h-screen">
        <h1 className="font-bold text-white">Result Prompt</h1>
        <p className="text-white">No hay prompt seleccionado</p>
        <Link className="btn btn-accent" to={"/"}>
          Volver al inicio
        </Link>
      </div>
    );
  }

  useEffect(() => {
    async function fetchData() {
      const response = await processPrompt();
      console.log(response);
    }

    fetchData();
  }, []);

  if (!result) {
    return (
      <div className="flex flex-col justify-center items-center gap-2 h-screen text-white">
        <p className="text-xl">Procesando</p>
        <span className="loading loading-infinity w-[5rem]"></span>
      </div>
    );
  }

  return (
    <div className="flex flex-col justify-center items-center gap-2 h-screen relative">
      <ConfettiExplosion
        force={0.8}
        duration={3000}
        particleCount={250}
        width={1600}
        zIndex={1}
        className="absolute left-1 top-3"
      />
      <h1 className="font-bold text-xl text-white">Felicidades, haz creado una nueva obra de arte!</h1>
      <p className="text-center text-white">{prompt.text}</p>
      <div className="bg-slate-500 w-[512px] h-[512px]">
        <img src={result.result.data.url} alt="Image generated by IA" width={512} height={512} />
      </div>
      <Link className="btn btn-accent" to={"/"}>
        Volver al inicio
      </Link>
      <ConfettiExplosion
        force={0.8}
        duration={3000}
        particleCount={250}
        width={1600}
        zIndex={1}
        className="absolute right-1 top-3"
      />
    </div>
  );
};

export default ResultPrompt;
